# Отчёт по лабораторной работе №3. NumPy

## Задание

Выполните следующие задания:

1. Открыли файл в Google Colab (используйте собственный форк репозитория).
2. Решили задачи.
3. Сохранили результат в наш репозиторий github в директорию ./les03
4. Создали pull request в репозиторий https://github.com/chebotarevsa/dap-2024. Назвали pull request в соответствии с форматом "<Номер лабораторной работы>  <Номер группы> <ФИО>"
5. Сдали работу в системе "Пегас", а в отчет указали ссылку на pull request

In [1]:
import numpy as np
np.version.version

'2.0.2'



```
# Выбран кодовый формат
```

1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [6]:
import numpy as np

arr = np.random.randint(-1000, 1000, size=(10,10))

print(arr)

print("\nMin - " + str(np.min(arr)))
print("Max - " + str(np.max(arr)))

[[ 470 -871 -159  -95 -408  587 -631  959  282  -16]
 [-467  424   30  994 -918  958  178  587  943  434]
 [ -54  476  624  201    8 -512 -845   59  494  344]
 [-329 -722  352 -143 -560  931  491  976  362  870]
 [-572  597  421  425  513 -495  613 -852  974  401]
 [ 111  139  771 -225 -691  106  470 -587 -731 -792]
 [-551 -962 -744 -959  984 -905  700   -1 -585  125]
 [ 334   85 -257   41  247  845  137 -882  604   88]
 [ 729  566   28 -666  713  658  192  709  497  925]
 [ 553  430  -41 -790  299 -911  669  108 -149 -893]]

Min - -962
Max - 994


2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [7]:
import numpy as np

size = 8

arr = np.zeros((size,size))

for i in range(size):
  for j in range(size):
    if i % 2 != 0 and j % 2 != 0:
      continue
    if i % 2 != 0 or j % 2 != 0:
      arr[i,j] = 1

print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [11]:
import numpy as np

z = np.arange(11)

print("Исходный массив:" + str(z))

for i in range(z.size):
  if z[i] > 3 and z[i] < 8:
    z[i] *= -1

print("Итоговый массив:" + str(z))

Исходный массив:[ 0  1  2  3  4  5  6  7  8  9 10]
Итоговый массив:[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


4. Найти среднее заначение строки матрицы и вычесть его из каждого елемента строки

In [19]:
import numpy as np

z = np.random.rand(5, 10)
average = np.mean(z, axis=1, keepdims=True)

print("Исходный массив\n" + str(z))
print("\nСреднее арифметическое\n" + str(average) + "\n")

print("Итоговый массив: \n" + str(np.subtract(z, average)))

Исходный массив
[[0.86283859 0.25887787 0.70910026 0.28958803 0.62439956 0.00303973
  0.13228175 0.03751049 0.80012238 0.019918  ]
 [0.66784734 0.04335423 0.40477681 0.34670893 0.84883199 0.24826637
  0.49369459 0.14541855 0.82662483 0.50065323]
 [0.70638009 0.26851271 0.71662143 0.46919565 0.06486245 0.72025178
  0.8241641  0.55423264 0.28905217 0.51688256]
 [0.93314065 0.31111151 0.24268545 0.25600367 0.86062878 0.24283748
  0.86782732 0.77449269 0.95363851 0.56678432]
 [0.42275066 0.74720926 0.22585001 0.9185954  0.3998469  0.81086596
  0.21580759 0.06701932 0.85729344 0.63700597]]

Средне арифметическое
[[0.37376767]
 [0.45261769]
 [0.51301556]
 [0.60091504]
 [0.53022445]]

Итоговый массив: 
[[ 0.48907093 -0.1148898   0.33533259 -0.08417963  0.2506319  -0.37072794
  -0.24148592 -0.33625718  0.42635472 -0.35384966]
 [ 0.21522965 -0.40926346 -0.04784087 -0.10590875  0.3962143  -0.20435132
   0.0410769  -0.30719914  0.37400714  0.04803555]
 [ 0.19336453 -0.24450285  0.20360587 -0.0438

5. Поменяйте 1 и 2 строки матрицы

In [24]:
import numpy as np

z = np.arange(25).reshape(5,5)
print("Исходное:\n" + str(z))

tmp = z[0][:].copy()
z[0][:] = z[1][:]
z[1][:] = tmp

print("\nИтог:\n" + str(z))

Исходное:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Итог:
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную

In [27]:
import numpy as np
import math

z = np.random.random((10,2))
res = z.copy()

res[:, 0] = np.sqrt(np.square(z[:, 0]) + np.square(z[:, 1]))
res[:, 1] = np.arctan2(z[:, 1], z[:, 0])

print("Исходное:\n", z)
print("\nРезультат (r, theta):\n", res)

# Ваш код здесь

Исходное:
 [[0.82314665 0.51114626]
 [0.57275242 0.98250739]
 [0.56417037 0.32366249]
 [0.08195694 0.5250819 ]
 [0.80088729 0.23215626]
 [0.14616462 0.39744587]
 [0.5982674  0.21655889]
 [0.71306698 0.66905744]
 [0.56185553 0.21265929]
 [0.19553328 0.69497263]]

Результат (r, theta):
 [[0.96893803 0.55569335]
 [1.13726254 1.04300814]
 [0.65041957 0.520854  ]
 [0.5314395  1.41596153]
 [0.83385669 0.28214102]
 [0.42347056 1.21838828]
 [0.63625595 0.34730443]
 [0.97780487 0.75356697]
 [0.6007542  0.36183091]
 [0.72195583 1.29653257]]


7. Заменить максимальный элемент массива на ноль

In [34]:
import numpy as np

z = np.random.random(10)
max = z.max()

print("Максимум:", max)
print("\nИсходное:\n", z)

z[(np.where(z == max))] = 0

print("\nРезультат:\n", z)

Максимум: 0.9931724248645607

Исходное:
 [0.77906135 0.82349758 0.2349426  0.68055953 0.57880554 0.46642701
 0.53693252 0.29084453 0.36360933 0.99317242]

Результат:
 [0.77906135 0.82349758 0.2349426  0.68055953 0.57880554 0.46642701
 0.53693252 0.29084453 0.36360933 0.        ]


8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [43]:
import numpy as np

z = np.ones(10)
i = np.random.randint(0,len(z),20)
chk = ""

print("Первый массив:\n", z)
print("\nВторой массив:\n", i)

for char in i:
  if str(char) in chk:
    continue
  else:
    z[char] += 1
    chk += str(char)

print("\nРезультат:\n", z)

Первый массив:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Второй массив:
 [5 0 4 7 4 8 0 1 0 9 4 6 3 3 6 0 5 9 6 0]

Результат:
 [2. 2. 1. 2. 2. 2. 2. 2. 2. 2.]


9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [60]:
import numpy as np

z = np.array([1,2,3,4,5])
result = []

for i in range(z.size - 1):
    result.append(int(z[i]))
    result.append(0)
    result.append(0)
    result.append(0)

result.append(int(z[z.size-1]))

arr = np.array(result)
print("Исходное:\n", z)
print("\nРезультат:\n", result)

Исходное:
 [1 2 3 4 5]

Результат:
 [1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5]


10. Найти ближайшее к заданному значению число в заданном массиве

In [74]:
import numpy as np

z = np.arange(100)
v = np.random.uniform(0,100)
chk = v - int(v)

print("Массив:\n", z)
print("Исходное число:\n", v)

print((z[int(v)], z[int(v) + 1])[chk > 0.5])

Массив:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Исходное число:
 71.32939722967221
71
